### ISSUE TITLE
Why another lisp?

### ISSUE THREAD

**Issue by Compro-Prasad** [rumlang/rum#104]

**Comment by avelino** [comment]
As described in the README[1] language was born for its an implementation of CLISP written in go, after a few days we saw an opportunity to create a language that is easily extensible and possible (Lua features with LISP syntax and functional) to be embarked on software Go.

[1] https://github.com/rumlang/rum#history

**Comment by Compro-Prasad** [comment]
I think it is a FAQ. There should be a special place for FAQ and link should be added on top of the README.
