### ISSUE TITLE
It's Common Lisp (or short, CL), not CLISP

### ISSUE THREAD

**Issue by wasamasa** [rumlang/rum#105]
See title.  [CLISP](https://clisp.sourceforge.io/) is an existing Common Lisp implementation, so it's rather confusing to see it mentioned over and over again.

That aside, CL has nothing to do with functional programming (it's multi-paradigmatic, with imperative and OO being the commonly used styles), there are far better-suited Lisp dialects for that purpose, like Scheme and Clojure.

**Comment by avelino** [comment]
It would be interesting for you to propose features that bring the language to a functional approach (since you don't think this is the right way)

**Comment by wasamasa** [comment]
Um, this is not a question, just me pointing out that your terminology is wrong.  If your response to this is that I suggest features (which is silly anyways, it's not the lack of features that make CL not the FP language to go for, it's that most CL code out there doesn't do it) for a language that's nowhere close to done, well, good luck with your project.
