### ISSUE TITLE
project name gin exist :(

### ISSUE THREAD

**Issue by avelino** [rumlang/rum#50]
Looking for open source projects VI that there is a project called gin[1] (Web framework) written in Golang, I think bad to continue with that name for the language.

The language was born in Florianópolis in the Canasvieiras neighbourhood, where a pirate boat for tourism, with this story I thought of calling the language of **Rum** (not registered trademark) to make the joke of *"Yo ho ho And a Bottle of rum"* used by pirates.

Extension: `.rum`

Do you like the name?

[1] https://github.com/gin-gonic/gin

**Comment by avelino** [comment]
@crgimenes @felipeweb

**Comment by crgimenes** [comment]
Rum was one of the names I suggested.
For me it's okay to change the name but it needs to be fast, we already have people from outside the group playing with the project.

_ ☠️ Fifteen men on a dead man's chest
Yo ho ho and a bottle of rum
Drink and the devil had done for the rest
Yo ho ho and a bottle of rum._

**Comment by fabriziomello** [comment]
+1 to do not conflict with other project name. Because of this mindset I love the open source community.

+1000 for the new name. Very good name and history.

**Comment by avelino** [comment]
Happy to have enjoyed, renamed
