### ISSUE TITLE
remove ' to array create

### ISSUE THREAD

**Issue by avelino** [rumlang/rum#55]
Lisp has several ways to do the same thing, the idea of rum is to be a simple lingaugem with a (clear) Form of doing operations (that is the philosophy of rum).

I find redundant to have two forms of array declaration
1. `array(10 20 30)`
1. `'10 20 30`

Let's remove the `'`?

**Comment by crgimenes** [comment]
to agree,
two ways of doing the same thing is bad

**Comment by felipeweb** [comment]
I agree
Em dom, 26 de nov de 2017 às 12:46, Cesar Gimenes <notifications@github.com>
escreveu:
